baseURL = "https://swift.jokerhub.cn"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir= false

theme = "hugo-theme-learn"
title = "Learn Swift"
metaDataFormat = "yaml"

[params]
  editURL = "https://github.com/wangzhizhou/LearnSwift/edit/master/docs/"
  description = "Swift学习"
  author = "王志舟"
  showVisitedLinks = false
  disableSearch = false
  disableNextPrev = false
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = true
  disableShortcutsTitle = true
  disableLandingPageButton = true
  disableLanguageSwitchingButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  ordersectionsby = "weight"
  themeVariant = "mine"
  custom_css = []
  titleSeparator = "-"
  
  # 自定义参数
  disableMathJax = false
  contentDirName = "docs"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub 仓库"
identifier = "ds"
url = "https://github.com/wangzhizhou/LearnSwift.git"
weight = 1

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-video'></i> SwiftUI 视频"
url = "https://developer.apple.com/videos/all-videos/?q=swiftui"
weight = 2

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-receipt'></i> SwiftUI 文档"
url = "https://developer.apple.com/documentation/swiftui/"
weight = 3

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> Learn 主题"
identifier = "learndoc"
url = "https://learn.netlify.app/en/"
weight = 4

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags 标签"
url = "/tags"
weight = 5

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fab fa-apple'></i> SwiftUI 官方教程(英文)"
identifier = "swiftUI tutorials"
url = "https://developer.apple.com/tutorials/swiftui/tutorials/"
weight = 6

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fab fa-sketch'></i> Font Awesome"
identifier = "fontawesome"
url = "https://fontawesome.com/icons?d=gallery&m=free"
weight = 7

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-book-open'></i> Swift 官网"
identifier = "swift"
url = "https://swift.org"
weight = 8

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-question-circle'></i> Apple 官方论坛"
identifier = "forums"
url = "https://developer.apple.com/forums/"
weight = 9

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-file-code'></i> Apple 示例代码"
identifier = "example code"
url = "https://developer.apple.com/sample-code"
weight = 10

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-folder'></i> Apple 官方文档"
identifier = "documentation"
url = "https://developer.apple.com/documentation/"
weight = 11

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-sun'></i> flaticon"
identifier = "flaticon"
url = "https://www.flaticon.com/"
weight = 12

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-archive'></i> SPM 查询"
identifier = "SPM Index"
url = "https://swiftpackageindex.com/"
weight = 13

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-paper-plane'></i> TOML 语法"
identifier = "TOML"
url = "https://toml.io"
weight = 14

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-book-reader'></i> SaltTiger 书籍下载"
identifier = "salttiger"
url= "https://salttiger.com"
weight = 15

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-solid fa-vr-cardboard'></i> visionOS"
identifier = 'visionOS'
url = "https://developer.apple.com/documentation/visionos"
weight = 16