#!/usr/bin/env bash
#-*- utf-8 -*-

pkill -9 hugo
hugo \
	--contentDir="docs" \
	--themesDir="themes" \
	--layoutDir="layouts" \
	--config="config.toml" \
	--ignoreCache=true \
	--disableFastRender \
	--navigateToChanged \
	--minify \
	--noBuildLock \
	--noHTTPCache \
	--printMemoryUsage \
	--printPathWarnings  \
	--printUnusedTemplates \
	server -D --bind "0.0.0.0" -p 1313 &
sleep 2s
open http://localhost:1313


